#!/bin/sh

# tento skript skompiluje a umiestni default_setter-y oboch zariadeni
#  - hydro_set_default
#  - termo_set_default
#  tieto subory su spustene pri ukonceni experimentov

cd  hydro/default_setter_src
make

cp dist/Debug/GNU-Linux-x86/hydro_set_default ../ 

cd  ../../termo/default_setter_src
make

cp dist/Debug/GNU-Linux-x86/termo_set_default ../ 