#!/bin/sh
export SCIHOME="$2"
export DISPLAY=:2.0
##xhost +
xterm -display :2.0 -e exit #'gnome-terminal -e \"scilab -d unix:0.0 -e "exec /var/www/udaq/model/runner.sce;"\"'
scilab -d unix:2.0 -nw -e "$1"
#xterm -e exit


#echo "/opt/scilab-5.2.1/bin/scilab -nw -e \"port=$1,sock_com;exit;\" -d unix" >/var/www/tmp/pipe
