// This file is released into the public domain
// Generated by builder.sce : Please, do not edit this file
//

termo_path = get_absolute_file_path('loader.sce');

// ulink previous function with same name
[bOK,ilib] = c_link('termo');if (bOK) then ulink(ilib),end
link(termo_path+'libtermo'+getdynlibext(),['termo'],'c');
// remove temp. variables on stack
clear termo_path;
clear get_file_path;
// ------------------------------------------------------
